export const GET_ALL_DOGS = "SET_ALL_RACES"
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS"
export const GET_DOGS_BY_NAME = "GET_DOGS_BY_NAME"
export const SORT_BY_NAME = "SORT_BY_NAME"
export const SORT_BY_WEIGHT = "SORT_BY_WEIGHT"
export const FILTER_BY_TEMPERAMENT = "FILTER_BY_TEMPERAMENT"
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN"
export const POST_DOG = "POST_DOG"


